### ISSUE TITLE
Doesnt work anymore in Chrome

### ISSUE THREAD

**Issue by qimmiq** [christianheyn/simple-masonry.js#2]
i don't know why, but my implemented version on my webproject only works in safari, but not in chrome. Some weeks ago everything was fine on both ends. Your demo Page is fine.

**Comment by christianwish** [comment]
Sorry for my late response.
Is everything fine in your project now?

I can't rebuild your error. Can you give me more information?

Best regards
Christian

**Comment by qimmiq** [comment]
Hey. was brauchst du denn an infos ? :) 
Ich muss gleich dazusagen, bin kein wirklicher pro :D aber ich versuch mich einfach gern an solchen Sachen.

**Comment by christianwish** [comment]
Hi.

Ist dein Fehler ein richtiger Error in der console? Oder ein Anzeigefehler im Frontend.
Hattest du etwas geändert und danach ist der Fehler gekommen?
Lädst du die Dateien per npm? Nutzt du browserify oder ähnliches?

Freundliche Grüße
Christian

**Comment by qimmiq** [comment]
hey. richtig spät :D 
aber ich hatte einfach verrafft das Chrome es nicht mag wenn man direkt aus github den code zieht. also mein Fehler ... danke dir
